title: Ernest Larvester nunca existio
author: Dutsiland
email: rrorropirrorro666@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Black Eyed Peas deberia tocar el intro de la nueva de Bob Esponja: Al Rescate

# social links
twitter_username: no uso twitter, cabron
github_username:  Dutsiland

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
